### ISSUE TITLE
tippy integration issues

### ISSUE THREAD

**Issue by dominik42** [stefanuebe/vaadin-fullcalendar#182]
### Bug Description

Today I integrate tippy.js into my Vaadin24 app with full-calendar v6.0.1 as mentioned [here](https://github.com/stefanuebe/vaadin-fullcalendar/wiki/FullCalendar-Examples#using-tippyjs-for-description-tooltips)
I follow the steps, but stumble upon a few small issues worth mentioned here in order to fix them and help other to jump start...

#### javascript error for the optional chaining operator
```
✘ [ERROR] Unexpected "!"
INFO c.v.b.devserver.DevServerOutputTracker
INFO c.v.b.devserver.DevServerOutputTracker       frontend/fullcalendar-with-tooltip.js:9:21:
INFO c.v.b.devserver.DevServerOutputTracker         9 │         this.calendar!.setOption("eventDidMount", e => {
INFO c.v.b.devserver.DevServerOutputTracker           ╵                      ^
```
After removing the '!' it works.

#### javascript error in the Browser JavaScript Console for `initTooltip(e:any)`

```
SyntaxError: missing ) after formal parameters
```

After modify the method signature and remove the type info `initTooltip(e)` it works.

#### wrong FullCalendarBuilder method name

The API mentioned [here](https://github.com/stefanuebe/vaadin-fullcalendar/wiki/FullCalendar-Examples#creating-a-subclass-of-fullcalendar-for-custom-mods) seems to be wrong and should be _withCustomType_ instead of _withCustomClass_

But beside those small issues, it works very well, THANK YOU 🙏

**Comment by stefanuebe** [comment]
Hi, thanks for the hints. Yes, the docs at that are a bit outdated, I will correct them. 

Regarding the first two issues. Here simply the file ending is outdated, it should be a `.ts`, making it a TypeScript file instead of a simple JavaScript file (`.js`). That should make the exclamation mark work. And then you also don't have the issue with the :any, which is a TypeScript type definition.

**Comment by stefanuebe** [comment]
Updated docs.
