### ISSUE TITLE
Question: filtering entries based on color

### ISSUE THREAD

**Issue by KejtKate** [stefanuebe/vaadin-fullcalendar#194]
Hi,

Just working on some web app with this add-on. I was wondering if there is some easy way to filter out entries based on color/other property to be shown in calendar?

I'm using in-memory provider. Was thinking to generate a new list of entries for each color to feed the provider, but that seems like a lot of work for. Also I thought of changing the provider to callback and getting a list of entry ids. 

Could you please suggest me some ideas? Which solution would be the best?

Thank you very much and best regards

**Comment by stefanuebe** [comment]
Without having it tested, I would propose to do that in the fetch method of you entry provider. Since you use the in memory one, you could subclass it, override the `Stream<T> fetch(@NonNull EntryQuery query)` method and filter the stream.

```java
public class FilterableInMemoryEntryProvider<T extends Entry> extends InMemoryEntryProvider<T extends Entry> {
    // constructors and so on ...

        @Override
    public Stream<T> fetch(@NonNull EntryQuery query) {
        return super.fetch(query).filter(entry -> "red".equals(entry.getColor()));
    }
}
```

You could of course make it more generic and let your custom provider take a callback, that can be used to filter the stream. 

```java
// class header as above

    private Predicate<T> predicate; // init via setter or constructor or ...

     @Override
    public Stream<T> fetch(@NonNull EntryQuery query) {
        Stream<T> stream = super.fetch(query);
        if(predicate != null) {
            stream = stream.filter(predicate);
        }
        return stream;
    }
```

The predicate can then be setup as in the first sample.

Would appreciate some feedback, if that approach worked.

**Comment by KejtKate** [comment]
Thank you so much! I will try to use this approch.

Before your answer I tried my approch with very simple code and it worked :) 

`        List<CalendarEntry> entries = new ArrayList<>();
        entries.add(entry1);
        entries.add(entry2);
        entries.add(entry3);
        entries.add(entry4);

        InMemoryEntryProvider<Entry> entryProvider = EntryProvider.inMemoryFrom(entries);
        calendar.setEntryProvider(entryProvider);

        List<Entry> pinkEntries = entryProvider.getEntries().stream().filter(entry -> entry.getColor().equals("pink")).toList();

        entryProvider.removeAllEntries();
        entryProvider.addEntries(pinkEntries);`

When using your code, do I have to removeAllEntries() and fetch again?

Idea is user can choose the color/multiple colors and this way filter them out.

**Comment by stefanuebe** [comment]
No, the remove all is not necessary. For the FC, there is no difference between an in memory and a lazy entry provider. It just uses the fetch methods, but does not care about where this data comes from. 

Therefore the only thing you will have to do is to set the filter to your entry provider (using custom api, that you define yourself on the subclassed EP) and call refreshAll on it (similar to the data provider for a grid). The FC should then fetch the data and use the newly set color.
